[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && npm ci --include=dev",
  "cd frontend && npm ci --include=dev"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && node dist/server.js"

